version: 1
datastore:
  filename: health.sqlite
scheduler:
  period_sec: 20
eventstore:
  receiver: http://acit3855-kafka-lab6a.eastus.cloudapp.azure.com:8080
  storage:  http://acit3855-kafka-lab6a.eastus.cloudapp.azure.com:8090
  processing:  http://acit3855-kafka-lab6a.eastus.cloudapp.azure.com:8100
  audit:  http://acit3855-kafka-lab6a.eastus.cloudapp.azure.com:8110